apiVersion: v1
kind: Service
metada:
  lebels:
    app: nginx-deployment
  name: nginx-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deployment
  type: NodePort
